/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Cleanup */
        post: operations["run_cleanup_api_v1_admin_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Info */
        get: operations["get_admin_info_api_v1_admin_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_v1_connections_get"];
        put?: never;
        /** Create Connection */
        post: operations["create_connection_api_v1_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_api_v1_connections__connection_id__get"];
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["delete_connection_api_v1_connections__connection_id__delete"];
        options?: never;
        head?: never;
        /** Update Connection */
        patch: operations["update_connection_api_v1_connections__connection_id__patch"];
        trace?: never;
    };
    "/connections/{connection_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection */
        post: operations["test_connection_api_v1_connections__connection_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Sql */
        post: operations["execute_sql_api_v1_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Query */
        post: operations["export_query_api_v1_queries__query_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Labels */
        get: operations["get_labels_api_v1_queries__query_id__labels_get"];
        put?: never;
        /** Upsert Label */
        post: operations["upsert_label_api_v1_queries__query_id__labels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/labels/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Labels */
        post: operations["query_labels_api_v1_queries__query_id__labels_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/labels/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Upsert Labels */
        post: operations["batch_upsert_labels_api_v1_queries__query_id__labels_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/labels/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Label */
        delete: operations["delete_label_api_v1_queries__query_id__labels__record_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/label-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Label Schema */
        get: operations["get_label_schema_api_v1_queries__query_id__label_schema_get"];
        /** Put Label Schema */
        put: operations["put_label_schema_api_v1_queries__query_id__label_schema_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Queries */
        get: operations["list_queries_api_v1_queries_get"];
        put?: never;
        /** Create Query */
        post: operations["create_query_api_v1_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Query */
        get: operations["get_query_api_v1_queries__query_id__get"];
        put?: never;
        post?: never;
        /** Delete Query */
        delete: operations["delete_query_api_v1_queries__query_id__delete"];
        options?: never;
        head?: never;
        /** Update Query */
        patch: operations["update_query_api_v1_queries__query_id__patch"];
        trace?: never;
    };
    "/queries/{query_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote Query */
        post: operations["promote_query_api_v1_queries__query_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Query */
        post: operations["execute_query_api_v1_queries__query_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Query History */
        get: operations["list_query_history_api_v1_query_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/render-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Render Rules */
        get: operations["list_render_rules_api_v1_render_rules_get"];
        put?: never;
        /** Create Render Rule */
        post: operations["create_render_rule_api_v1_render_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/render-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Render Rule */
        get: operations["get_render_rule_api_v1_render_rules__rule_id__get"];
        put?: never;
        post?: never;
        /** Delete Render Rule */
        delete: operations["delete_render_rule_api_v1_render_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Render Rule */
        patch: operations["update_render_rule_api_v1_render_rules__rule_id__patch"];
        trace?: never;
    };
    "/queries/{query_id}/trajectories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggregate Query Trajectories */
        post: operations["aggregate_query_trajectories_api_v1_queries__query_id__trajectories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/view-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get View Config */
        get: operations["get_view_config_api_v1_queries__query_id__view_config_get"];
        /** Put View Config */
        put: operations["put_view_config_api_v1_queries__query_id__view_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminInfoResponse */
        AdminInfoResponse: {
            /** Version */
            version: string;
            /** Data Dir */
            data_dir: string;
            /** Db Path */
            db_path: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Scheduler Jobs */
            scheduler_jobs: components["schemas"]["SchedulerJobRead"][];
            /** Connections Count */
            connections_count: number;
            /** Named Queries Count */
            named_queries_count: number;
        };
        /** CleanupReport */
        CleanupReport: {
            /** Expired Queries Deleted */
            expired_queries_deleted: number;
            /** History Records Deleted */
            history_records_deleted: number;
            /** Cascade Label Records Deleted */
            cascade_label_records_deleted: number;
            /** Cascade Analyses Deleted */
            cascade_analyses_deleted: number;
            /** Dry Run */
            dry_run: boolean;
        };
        /** CleanupRequest */
        CleanupRequest: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** CodeRender */
        CodeRender: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code";
            /**
             * Language
             * @default plain
             */
            language: string;
        } & {
            [key: string]: unknown;
        };
        /** ColumnRead */
        ColumnRead: {
            /** Name */
            name: string;
            /** Sql Type */
            sql_type: string;
            /**
             * Inferred Type
             * @enum {string}
             */
            inferred_type: "text" | "integer" | "float" | "boolean" | "json" | "timestamp" | "binary" | "unknown";
        };
        /** ConnectionCreate */
        ConnectionCreate: {
            /** Name */
            name: string;
            /**
             * Db Type
             * @default mysql
             * @constant
             */
            db_type: "mysql";
            /** Host */
            host?: string | null;
            /**
             * Port
             * @default 3306
             */
            port: number | null;
            /** Database */
            database: string;
            /** Username */
            username?: string | null;
            /** Extra Params */
            extra_params?: {
                [key: string]: string | number | boolean | null;
            } | null;
            /**
             * Default Timeout
             * @default 30
             */
            default_timeout: number;
            /**
             * Default Row Limit
             * @default 10000
             */
            default_row_limit: number;
            /** Password */
            password?: string | null;
        };
        /** ConnectionListResponse */
        ConnectionListResponse: {
            /** Items */
            items: components["schemas"]["ConnectionRead"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** ConnectionRead */
        ConnectionRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Db Type */
            db_type: string;
            /** Host */
            host: string | null;
            /** Port */
            port: number | null;
            /** Database */
            database: string;
            /** Username */
            username: string | null;
            /** Extra Params */
            extra_params: {
                [key: string]: string | number | boolean | null;
            } | null;
            /** Default Timeout */
            default_timeout: number;
            /** Default Row Limit */
            default_row_limit: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Tested At */
            last_tested_at: string | null;
            /** Last Test Ok */
            last_test_ok: boolean | null;
        };
        /** ConnectionTestResponse */
        ConnectionTestResponse: {
            /** Ok */
            ok: boolean;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Server Version */
            server_version?: string | null;
            /**
             * Tested At
             * Format: date-time
             */
            tested_at: string;
            /** Error */
            error?: string | null;
        };
        /** ConnectionUpdate */
        ConnectionUpdate: {
            /** Name */
            name?: string | null;
            /** Db Type */
            db_type?: "mysql" | null;
            /** Host */
            host?: string | null;
            /** Port */
            port?: number | null;
            /** Database */
            database?: string | null;
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
            /** Extra Params */
            extra_params?: {
                [key: string]: string | number | boolean | null;
            } | null;
            /** Default Timeout */
            default_timeout?: number | null;
            /** Default Row Limit */
            default_row_limit?: number | null;
        };
        /** EnumRender */
        EnumRender: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "enum";
            /** Colors */
            colors?: {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** ExecuteRequest */
        ExecuteRequest: {
            /** Connection Id */
            connection_id: number;
            /** Sql */
            sql: string;
            /**
             * Save As Temporary
             * @default true
             */
            save_as_temporary: boolean;
            /** Timeout */
            timeout?: number | null;
            /** Row Limit */
            row_limit?: number | null;
        };
        /** ExecutionInfo */
        ExecutionInfo: {
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Row Count */
            row_count: number;
            /** Truncated */
            truncated: boolean;
        };
        /** ExecutionResult */
        ExecutionResult: {
            /** Query Id */
            query_id: number;
            /** Is Temporary */
            is_temporary: boolean;
            execution: components["schemas"]["ExecutionInfo"];
            /** Columns */
            columns: components["schemas"]["ColumnRead"][];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Suggested Field Renders */
            suggested_field_renders: {
                [key: string]: components["schemas"]["TextRender"] | components["schemas"]["MarkdownRender"] | components["schemas"]["JsonRender"] | components["schemas"]["CodeRender"] | components["schemas"]["TimestampRender"] | components["schemas"]["TagRender"] | components["schemas"]["EnumRender"];
            };
            suggested_trajectory_config?: components["schemas"]["TrajectoryConfig"] | null;
            /** Warnings */
            warnings: components["schemas"]["WarningRead"][];
        };
        /** ExportRequest */
        ExportRequest: {
            /**
             * Format
             * @enum {string}
             */
            format: "csv" | "xlsx";
            /**
             * Include Labels
             * @default true
             */
            include_labels: boolean;
            /**
             * Json Serialization
             * @default string
             * @constant
             */
            json_serialization: "string";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Metadata Db */
            metadata_db: string;
            /** Uptime Seconds */
            uptime_seconds: number;
        };
        /** JsonRender */
        JsonRender: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "json";
            /**
             * Collapsed
             * @default true
             */
            collapsed: boolean;
        } & {
            [key: string]: unknown;
        };
        /** LabelBatchError */
        LabelBatchError: {
            /** Row Identity */
            row_identity: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        /** LabelBatchResult */
        LabelBatchResult: {
            /** Affected */
            affected: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors?: components["schemas"]["LabelBatchError"][];
        };
        /** LabelBatchUpsert */
        LabelBatchUpsert: {
            /** Row Identities */
            row_identities?: string[];
            /** Field Key */
            field_key: string;
            /** Value */
            value: unknown | null;
        };
        /** LabelOption */
        LabelOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Color */
            color?: string | null;
        };
        /** LabelRecordRead */
        LabelRecordRead: {
            /** Record Id */
            record_id: number;
            /** Query Id */
            query_id: number;
            /** Row Identity */
            row_identity: string;
            /** Field Key */
            field_key: string;
            /** Value */
            value: unknown;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LabelRecordUpsert */
        LabelRecordUpsert: {
            /** Row Identity */
            row_identity: string;
            /** Field Key */
            field_key: string;
            /** Value */
            value: unknown | null;
        };
        /** LabelRowsQuery */
        LabelRowsQuery: {
            /** Row Identities */
            row_identities?: string[];
        };
        /** LabelSchemaPayload */
        LabelSchemaPayload: {
            /** Fields */
            fields?: (components["schemas"]["SingleSelectField"] | components["schemas"]["MultiSelectField"] | components["schemas"]["TextField"])[];
        };
        /** LabelSchemaRead */
        LabelSchemaRead: {
            /** Query Id */
            query_id: number;
            /** Fields */
            fields: (components["schemas"]["SingleSelectField"] | components["schemas"]["MultiSelectField"] | components["schemas"]["TextField"])[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Cascade Deleted Records
             * @default 0
             */
            cascade_deleted_records: number;
        };
        /** LabelsByRowResponse */
        LabelsByRowResponse: {
            /** Labels By Row */
            labels_by_row: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** MarkdownRender */
        MarkdownRender: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "markdown";
        } & {
            [key: string]: unknown;
        };
        /** MultiSelectField */
        MultiSelectField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multi_select";
            /** Options */
            options?: components["schemas"]["LabelOption"][];
        };
        /** NamedQueryCreate */
        NamedQueryCreate: {
            /** Connection Id */
            connection_id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Sql Text */
            sql_text: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /** NamedQueryListResponse */
        NamedQueryListResponse: {
            /** Items */
            items: components["schemas"]["NamedQueryRead"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** NamedQueryPromote */
        NamedQueryPromote: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** NamedQueryRead */
        NamedQueryRead: {
            /** Id */
            id: number;
            /** Connection Id */
            connection_id: number;
            /** Connection Name */
            connection_name: string;
            /** Name */
            name: string | null;
            /** Description */
            description: string | null;
            /** Sql Text */
            sql_text: string;
            /** Is Named */
            is_named: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Executed At */
            last_executed_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Label Record Count */
            label_record_count: number;
            /** Llm Analysis Count */
            llm_analysis_count: number;
        };
        /** NamedQueryUpdate */
        NamedQueryUpdate: {
            /** Name */
            name?: string;
            /** Description */
            description?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** Pagination */
        Pagination: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** QueryExecuteRequest */
        QueryExecuteRequest: {
            /** Timeout */
            timeout?: number | null;
            /** Row Limit */
            row_limit?: number | null;
        };
        /** QueryHistoryListResponse */
        QueryHistoryListResponse: {
            /** Items */
            items: components["schemas"]["QueryHistoryRead"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** QueryHistoryRead */
        QueryHistoryRead: {
            /** Id */
            id: number;
            /** Connection Id */
            connection_id: number;
            /** Sql Text */
            sql_text: string;
            /** Row Count */
            row_count: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Query Id */
            query_id: number | null;
        };
        /** RenderRuleCreate */
        RenderRuleCreate: {
            /** Match Pattern */
            match_pattern: string;
            /**
             * Match Type
             * @default exact
             * @enum {string}
             */
            match_type: "exact" | "prefix" | "suffix" | "regex";
            /** Render Config */
            render_config: components["schemas"]["TextRender"] | components["schemas"]["MarkdownRender"] | components["schemas"]["JsonRender"] | components["schemas"]["CodeRender"] | components["schemas"]["TimestampRender"] | components["schemas"]["TagRender"] | components["schemas"]["EnumRender"] | components["schemas"]["TrajectoryConfigRule"];
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** RenderRuleRead */
        RenderRuleRead: {
            /** Match Pattern */
            match_pattern: string;
            /**
             * Match Type
             * @default exact
             * @enum {string}
             */
            match_type: "exact" | "prefix" | "suffix" | "regex";
            /** Render Config */
            render_config: components["schemas"]["TextRender"] | components["schemas"]["MarkdownRender"] | components["schemas"]["JsonRender"] | components["schemas"]["CodeRender"] | components["schemas"]["TimestampRender"] | components["schemas"]["TagRender"] | components["schemas"]["EnumRender"] | components["schemas"]["TrajectoryConfigRule"];
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RenderRuleUpdate */
        RenderRuleUpdate: {
            /** Match Pattern */
            match_pattern?: string | null;
            /** Match Type */
            match_type?: ("exact" | "prefix" | "suffix" | "regex") | null;
            /** Render Config */
            render_config?: (components["schemas"]["TextRender"] | components["schemas"]["MarkdownRender"] | components["schemas"]["JsonRender"] | components["schemas"]["CodeRender"] | components["schemas"]["TimestampRender"] | components["schemas"]["TagRender"] | components["schemas"]["EnumRender"] | components["schemas"]["TrajectoryConfigRule"]) | null;
            /** Priority */
            priority?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** SchedulerJobRead */
        SchedulerJobRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Trigger */
            trigger: string;
            /** Next Run */
            next_run: string | null;
        };
        /** SingleSelectField */
        SingleSelectField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "single_select";
            /** Options */
            options?: components["schemas"]["LabelOption"][];
        };
        /** SortConfig */
        SortConfig: {
            /** Column */
            column: string;
            /**
             * Direction
             * @default asc
             * @enum {string}
             */
            direction: "asc" | "desc";
        };
        /** TableConfig */
        TableConfig: {
            /** Column Widths */
            column_widths?: {
                [key: string]: number;
            };
            /** Hidden Columns */
            hidden_columns?: string[];
            /** Frozen Columns */
            frozen_columns?: string[];
            /** Sort */
            sort?: components["schemas"]["SortConfig"][];
        } & {
            [key: string]: unknown;
        };
        /** TagRender */
        TagRender: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tag";
        } & {
            [key: string]: unknown;
        };
        /** TextField */
        TextField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /** TextRender */
        TextRender: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        } & {
            [key: string]: unknown;
        };
        /** TimestampRender */
        TimestampRender: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "timestamp";
            /**
             * Format
             * @default YYYY-MM-DD HH:mm:ss
             */
            format: string;
        } & {
            [key: string]: unknown;
        };
        /** Trajectory */
        Trajectory: {
            /** Group Key */
            group_key: string;
            /** Message Count */
            message_count: number;
            /** Messages */
            messages: components["schemas"]["TrajectoryMessage"][];
        };
        /** TrajectoryAggregateRequest */
        TrajectoryAggregateRequest: {
            /**
             * Use Saved Config
             * @default true
             */
            use_saved_config: boolean;
            trajectory_config?: components["schemas"]["TrajectoryConfig"] | null;
            /** Timeout */
            timeout?: number | null;
            /** Row Limit */
            row_limit?: number | null;
        };
        /** TrajectoryAggregateResponse */
        TrajectoryAggregateResponse: {
            /** Trajectories */
            trajectories: components["schemas"]["Trajectory"][];
            /** Warnings */
            warnings: components["schemas"]["WarningRead"][];
        };
        /** TrajectoryConfig */
        TrajectoryConfig: {
            /** Group By */
            group_by: string;
            /** Role Column */
            role_column: string;
            /** Content Column */
            content_column: string;
            /** Tool Calls Column */
            tool_calls_column?: string | null;
            /** Order By */
            order_by?: string | null;
            /**
             * Order Direction
             * @default asc
             * @enum {string}
             */
            order_direction: "asc" | "desc";
        };
        /** TrajectoryConfigRule */
        TrajectoryConfigRule: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "trajectory_config";
            /**
             * Field
             * @enum {string}
             */
            field: "group_by" | "role_column" | "content_column" | "tool_calls_column" | "order_by";
            /** Order Direction */
            order_direction?: ("asc" | "desc") | null;
        };
        /** TrajectoryMessage */
        TrajectoryMessage: {
            /** Row Identity */
            row_identity: string;
            /** Role */
            role: string;
            /** Content */
            content: unknown;
            /** Tool Calls */
            tool_calls?: unknown | null;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewConfigPayload */
        ViewConfigPayload: {
            /** Field Renders */
            field_renders?: {
                [key: string]: components["schemas"]["TextRender"] | components["schemas"]["MarkdownRender"] | components["schemas"]["JsonRender"] | components["schemas"]["CodeRender"] | components["schemas"]["TimestampRender"] | components["schemas"]["TagRender"] | components["schemas"]["EnumRender"];
            };
            table_config?: components["schemas"]["TableConfig"];
            trajectory_config?: components["schemas"]["TrajectoryConfig"] | null;
            /** Trajectory Config Source */
            trajectory_config_source?: ("manual" | "suggested") | null;
            /** Row Identity Column */
            row_identity_column?: string | null;
        };
        /** ViewConfigRead */
        ViewConfigRead: {
            /** Field Renders */
            field_renders?: {
                [key: string]: components["schemas"]["TextRender"] | components["schemas"]["MarkdownRender"] | components["schemas"]["JsonRender"] | components["schemas"]["CodeRender"] | components["schemas"]["TimestampRender"] | components["schemas"]["TagRender"] | components["schemas"]["EnumRender"];
            };
            table_config?: components["schemas"]["TableConfig"];
            trajectory_config?: components["schemas"]["TrajectoryConfig"] | null;
            /** Trajectory Config Source */
            trajectory_config_source?: ("manual" | "suggested") | null;
            /** Row Identity Column */
            row_identity_column?: string | null;
            /** Query Id */
            query_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WarningRead */
        WarningRead: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_cleanup_api_v1_admin_cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_info_api_v1_admin_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInfoResponse"];
                };
            };
        };
    };
    list_connections_api_v1_connections_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connection_api_v1_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_api_v1_connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_api_v1_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connection_api_v1_connections__connection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_v1_connections__connection_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_sql_api_v1_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_query_api_v1_queries__query_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Exported query result file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_labels_api_v1_queries__query_id__labels_get: {
        parameters: {
            query?: {
                row_identities?: string | null;
                row_identity?: string[] | null;
            };
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelsByRowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_label_api_v1_queries__query_id__labels_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelRecordUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelRecordRead"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_labels_api_v1_queries__query_id__labels_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelRowsQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelsByRowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_upsert_labels_api_v1_queries__query_id__labels_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelBatchUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelBatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_label_api_v1_queries__query_id__labels__record_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_label_schema_api_v1_queries__query_id__label_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelSchemaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_label_schema_api_v1_queries__query_id__label_schema_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelSchemaPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelSchemaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_queries_api_v1_queries_get: {
        parameters: {
            query?: {
                connection_id?: number | null;
                is_named?: boolean | null;
                search?: string | null;
                include_expired?: boolean;
                order_by?: "created_at" | "last_executed_at";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_query_api_v1_queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedQueryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_query_api_v1_queries__query_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_query_api_v1_queries__query_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_query_api_v1_queries__query_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedQueryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_query_api_v1_queries__query_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedQueryPromote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_query_api_v1_queries__query_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["QueryExecuteRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_query_history_api_v1_query_history_get: {
        parameters: {
            query?: {
                connection_id?: number | null;
                page?: number;
                page_size?: number;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryHistoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_render_rules_api_v1_render_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRuleRead"][];
                };
            };
        };
    };
    create_render_rule_api_v1_render_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_render_rule_api_v1_render_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_render_rule_api_v1_render_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_render_rule_api_v1_render_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aggregate_query_trajectories_api_v1_queries__query_id__trajectories_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TrajectoryAggregateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrajectoryAggregateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_config_api_v1_queries__query_id__view_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_view_config_api_v1_queries__query_id__view_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewConfigPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
